image: ghcr.io/zephyrproject-rtos/ci:latest

stages:
  - build

variables:
  CMAKE_PREFIX_PATH: "/opt/toolchains"

before_script:
  - west init -l .
  - west update -o=--depth=1 -n

build:
  stage: build
  script:
    - west build -b pluto_pico app
    # Copy zephyr.uf2 to root directory and name it rpi_pico.uf2
    - find -name '*.uf2' -exec cp {} pluto_pico.uf2 \;
  artifacts:
    paths:
      - build/
      - pluto_pico.uf2
    expire_in: 1 week
